<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Custely.DAL\Custely.DAL.csproj" />
	  <ProjectReference Include="..\Custely.ENTITY\Custely.ENTITY.csproj" />
  </ItemGroup>

</Project>
