<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistPuntos_Heladeria.BLL\SistPuntos_Heladeria.BLL.csproj" />
    <ProjectReference Include="..\SistPuntos_Heladeria.ENTITY\SistPuntos_Heladeria.ENTITY.csproj" />
  </ItemGroup>

</Project>